apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    istio-injection: enabled
    istio.io/rev: asm-managed 
  annotations:
    mesh.cloud.google.com/proxy: '{"managed":"true"}'
    description: "Namespace para desplegar las aplicaciones multi-cluster."
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-v1
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
      version: v1
  template:
    metadata:
      labels:
        app: consumer
        version: v1
    spec:
      containers:
      - name: consumer
        image: d4rkghost47/python-multicluster-consumer:0.0.3
        ports:
        - containerPort: 8000
        env:
        - name: CLUSTER_NAME
          value: "gke-us"
        - name: SERVICE_VERSION
          value: "v1"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            cpu: "10m"
            memory: "32Mi"
          limits:
            cpu: "100m"
            memory: "128Mi" 
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          runAsUser: 10001
          runAsGroup: 3000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
          privileged: false
          readOnlyRootFilesystem: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-v2
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
      version: v2
  template:
    metadata:
      labels:
        app: consumer
        version: v2
    spec:
      containers:
      - name: consumer
        image: d4rkghost47/python-multicluster-consumer:0.0.3
        ports:
        - containerPort: 8000
        env:
        - name: CLUSTER_NAME
          value: "gke-us"
        - name: SERVICE_VERSION
          value: "v2"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            cpu: "10m"
            memory: "32Mi"
          limits:
            cpu: "100m"
            memory: "128Mi" 
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          runAsUser: 10001
          runAsGroup: 3000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
          privileged: false
          readOnlyRootFilesystem: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-v3
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
      version: v3
  template:
    metadata:
      labels:
        app: consumer
        version: v3
    spec:
      containers:
      - name: consumer
        image: d4rkghost47/python-multicluster-consumer:0.0.3
        ports:
        - containerPort: 8000
        env:
        - name: CLUSTER_NAME
          value: "gke-us"
        - name: SERVICE_VERSION
          value: "v3"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            cpu: "10m"
            memory: "32Mi"
          limits:
            cpu: "100m"
            memory: "128Mi" 
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          runAsUser: 10001
          runAsGroup: 3000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
          privileged: false
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
  namespace: app
  labels:
    app: consumer
    service: consumer
spec:
  type: ClusterIP 
  selector:
    app: consumer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: http